# Generated by Django 3.2.19 on 2023-05-26 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('goal_1', models.CharField(blank=True, max_length=250)),
                ('goal_2', models.CharField(blank=True, max_length=250)),
                ('goal_3', models.CharField(blank=True, max_length=250)),
                ('deadline', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='todo', max_length=11)),
                ('color', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='red', max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
