# Generated by Django 3.2.19 on 2023-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
