# Generated by Django 3.2.19 on 2023-05-24 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='goal_1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='goal_2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='goal_3',
        ),
        migrations.AddField(
            model_name='projects',
            name='goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=' ', size=3),
            preserve_default=False,
        ),
    ]
