# Generated by Django 3.2.19 on 2023-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0002_projects_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
