# Generated by Django 3.2.19 on 2023-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230516_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
